services:
  dind:
    environment:
      # s6-overlay / SSH / DinD 控制变量
      - PUID=${PUID:-911}
      - PGID=${PGID:-911}
      - START_DOCKER=${START_DOCKER:-true}
      - TZ=${TZ:-Asia/Shanghai}
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    shm_size: 8gb
    image: "localbuild/xfl/dind:ubuntu"
    container_name: dind
    pull_policy: build
    build:
      context: ./build_resource
      dockerfile: ./Dockerfile
      additional_contexts:
        ubuntu-quick: https://github.com/xfl12345/ubuntu-quick.git#79c0cd1b9aafaacc2ad2bd5cc38ec168e540e418
        openssh-server: https://github.com/linuxserver/docker-openssh-server.git#879130ad04f326a039c173bf40b852a0f7e4485d
    volumes:
      - /dev/dri:/dev/dri
      - /lib/modules:/lib/modules:ro
      - ./volume/moved_root/config:/config
      - ./volume/moved_root/var/lib/docker:/var/lib/docker
    network_mode: bridge
    restart: unless-stopped
