services:
  dind:
    image: "${REGISTRY}/${IMAGE_NAME}:${TAG_SUFFIX}"
    container_name: dind
    pull_policy: build
    build:
      context: ./build_resource
      dockerfile: ./Dockerfile
      additional_contexts:
        ubuntu-quick: https://github.com/xfl12345/ubuntu-quick.git#79c0cd1b9aafaacc2ad2bd5cc38ec168e540e418
        openssh-server: https://github.com/linuxserver/docker-openssh-server.git#879130ad04f326a039c173bf40b852a0f7e4485d
      # platforms:
      #   - linux/amd64
      #   - linux/arm64
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
      args:
        # 开启 BuildKit 内联缓存，对后续拉取镜像加速很有用
        - BUILDKIT_INLINE_CACHE=1 
