services:
  dind:
    environment:
      # s6-overlay / SSH / DinD 控制变量
      - PUID=${PUID:-911}
      - PGID=${PGID:-911}
      - START_DOCKER=${START_DOCKER:-true}
      - TZ=${TZ:-Asia/Shanghai}
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    shm_size: 8gb
    image: ghcr.io/xfl12345/dind
    container_name: dind
    # image: ghcr.nju.edu.cn/xfl12345/dind
    pull_policy: always
    volumes:
      - /dev/dri:/dev/dri
      - /lib/modules:/lib/modules:ro
      - ./volume/moved_root/config:/config
      - ./volume/moved_root/var/lib/docker:/var/lib/docker
    network_mode: bridge
    restart: unless-stopped
